site_name: DDEV-Local Documentation
repo_url: https://github.com/drud/ddev
repo_name: GitHub
edit_uri: blob/master/docs/
copyright: Localdev Foundation
theme:
  name: 'material'
  palette:
    primary: 'light-blue'
extra_javascript:
  - 'assets/jquery-3.5.1.min.js'
  - 'assets/extra.js'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br
    - pymdownx.details
    - pymdownx.superfences
    - meta
plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en
nav:
  - 'Home': 'index.md'
  - 'Installing ddev':
    - 'Installing Docker': 'users/docker_installation.md'
    - 'Adding Shell Completion (bash, zsh, etc.)': 'users/shell-completion.md'
    - 'Working in Special Environments': 'users/special-environments.md'
    - 'Improving Performance': 'users/performance.md'
    - 'Uninstalling ddev': 'users/uninstall.md'
  - 'ddev Basics':
    - 'How DDEV Works': 'users/topics/how_ddev_works.md'
    - 'Using the CLI': 'users/cli-usage.md'
    - 'Adding ddev Hooks': 'users/extending-commands.md'
    - 'Using Developer Tools with ddev': 'users/developer-tools.md'
    - 'Step-Debugging PHP': 'users/step-debugging.md'
    - 'Profiling with Blackfire': 'users/blackfire-profiling.md'
    - 'Profiling with xhprof': 'users/xhprof-profiling.md'
    - 'Profiling with Xdebug': 'users/xdebug-profiling.md'
    - 'Troubleshooting': 'users/troubleshooting.md'
    - 'Frequently-Asked Questions (FAQ)': 'users/faq.md'
    - 'Configuring ddev': 'users/extend/config_yaml.md'
    - 'Choosing Database Server Types': 'users/extend/database_types.md'
    - 'Adding Additional Hostnames': 'users/extend/additional-hostnames.md'
    - 'Alternate Uses of ddev': 'users/alternate-uses.md'
  - 'Extending ddev':
    - 'Extending and Customizing Environments': 'users/extend/customization-extendibility.md'
    - 'Adding Additional Services': 'users/extend/additional-services.md'
    - 'Defining Custom Services': 'users/extend/custom-compose-files.md'
    - 'Customizing Docker Images': 'users/extend/customizing-images.md'
    - 'Adding Custom Commands': 'users/extend/custom-commands.md'
    - 'Configuring Containers': 'users/extend/in-container-configuration.md'
    - 'Adding Custom TLS Certificates': 'users/extend/custom-tls-certificates.md'
  - 'Integrating with Hosting Providers':
    - 'Introduction': 'users/providers/provider-introduction.md'
    - 'Acquia': 'users/providers/acquia.md'
    - 'Pantheon': 'users/providers/pantheon.md'
    - 'Platform.sh': 'users/providers/platform.md'
  - 'Specific Guides':
      - 'Configuring a CMS': 'users/topics/cms_specific_help.md'
      - 'Managing Databases': 'users/topics/database_management.md'
      - 'Using Gitpod.io': 'users/topics/gitpod.md'
      - 'Integrating with PhpStorm': 'users/topics/phpstorm.md'
      - 'Sharing Your Project': 'users/topics/sharing.md'
      - 'Configuring Web Servers': 'users/topics/webserver.md'
      - "Understanding the .ddev Directory": 'users/topics/whats_in_ddev_dir.md'
      - 'Version History': 'users/topics/version-history.md'
